Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"
  config.vm.network :private_network, ip: "192.168.70.10"

  # add CPU and RAM
  config.vm.provider "virtualbox" do |v|
    v.name = "mysql-nginx.vm.localhost"
    v.memory = 2096
    v.cpus = 2
  end

  # disable swap
  config.vm.provision "shell", inline: "swapoff -a"

  # use ansible provisioner
  # give vagrant path to main playbook
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/main.yml"
  end

end
