---
- hosts: all
  gather_facts: no
  remote_user: vagrant

  tasks:

  - name: create /opt/volumes/mysql/data
    file:
      path: /opt/volumes/mysql/data
      state: directory
      mode: 0755
    become: true

  # ansible module for docker
  - pip:
      name: docker-py
    become: true

  # - name: make / shared volume
  #   command: mount --make-shared /
  #   become: true

  - name: start mysql server
    docker_container:
      name: mysql
      image: mysql:5
      detach: yes
      restart_policy: unless-stopped
      ports:
        - "3306:3306"
      volumes:
        - /opt/volumes/mysql/data:/var/lib/mysql
      env:
        MYSQL_ROOT_PASSWORD: rancher
        MYSQL_DATABASE: rancher
        MYSQL_USER: rancher
        MYSQL_PASSWORD: rancher
    become: true

  - name: create /opt/volumes/nginx
    file:
      path: /opt/volumes/nginx
      state: directory
      mode: 0755
    become: true

  - command: cp /vagrant/provisioning/nginx/rancher.conf /opt/volumes/nginx/.
    become: true

  - name: start nginx
    docker_container:
      name: nginx
      image: nginx
      detach: yes
      restart_policy: unless-stopped
      ports:
        - "8080:8080"
        - "80:80"
      volumes:
        - /opt/volumes/nginx/rancher.conf:/etc/nginx/conf.d/default.conf
    become: true
